import './sso'
import './accounts'

import '/imports/api/Experiences'
import '/imports/api/Experiences/server/experiencesPublications'
import '/imports/api/Experiences/experiencesMethods'
import '/imports/api/Organizations'
import '/imports/api/Organizations/server/organizationsPublications'
import '/imports/api/Organizations/organizationsMethods'
import '/imports/api/Positions'
import '/imports/api/Positions/interestExpressionMethods'
import '/imports/api/Positions/server/positionsMethods'
import '/imports/api/Positions/server/positionsPublications'
import '/imports/api/Search'
import '/imports/api/Tags'
import '/imports/api/Tags/server/tagsPublications'
import '/imports/api/Users'
import '/imports/api/Users/server/usersPublications'
import '/imports/api/Users/usersMethods'

// Import the seed initiator so it is included in the build bundle
import '/imports/seeds'
